### ISSUE TITLE
Installation problem: "Conclusion: install php-http/httplug v1.1.0"

### ISSUE THREAD

**Issue by jsuwala** [OneOffTech/geoserver-client-php#15]
Hi there

When I run the default documented installation command `composer.phar require php-http/guzzle6-adapter guzzlehttp/psr7 oneofftech/geoserver-client-php`, I get the following message:
```
Using version ^2.0 for php-http/guzzle6-adapter
Using version ^1.6 for guzzlehttp/psr7
Using version ^0.2.1 for oneofftech/geoserver-client-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for oneofftech/geoserver-client-php ^0.2.1 -> satisfiable by oneofftech/geoserver-client-php[v0.2.1].
    - oneofftech/geoserver-client-php v0.2.1 requires php-http/client-implementation ^1.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1].
    - php-http/guzzle6-adapter v2.0.0 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[2.1.0, v2.0.0].
    - php-http/guzzle6-adapter v2.0.1 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[2.1.0, v2.0.0].
    - Can only install one of: php-http/httplug[v1.1.0, 2.1.0].
    - Can only install one of: php-http/httplug[v2.0.0, v1.1.0].
    - Conclusion: install php-http/httplug v1.1.0


Installation failed, deleting ./composer.json.
```

After a bunch of google searches, I found this reference issuehttps://github.com/hwi/HWIOAuthBundle/issues/1457 which looks like there's problems with support for HTTPlug 2.0. Based on this, I modified my command and got it working with this:

`composer require php-http/guzzle6-adapter:~1 php-http/httplug:^1.1.0 guzzlehttp/psr7 oneofftech/geoserver-client-php`

Perhaps it would be good to update the readme file and the installation instructions file?

**Comment by avvertix** [comment]
I will look for compatibility issues of version ^2.0 for php-http/guzzle6-adapter. If there are some I will change the readme as you said, otherwise I might open for both versions

**Comment by avvertix** [comment]
Seems that were some minor compatibility issues, but in #16 I was able to sort those out. If you want you can use version 2.0 for the Guzzle adapter. The only edit required change to the installation is to add `http-interop/http-factory-guzzle`

**Comment by jsuwala** [comment]
Thanks @avvertix - much appreciated.
