### ISSUE TITLE
Uploading zip file

### ISSUE THREAD

**Issue by FrankOssie** [OneOffTech/geoserver-client-php#20]
When using the upload, the geoserver responds with "Not Acceptable" but the file will be put on the geoserver.

GeoServer version: 2.17.0

**Comment by avvertix** [comment]
Hi @FrankOssie would be nice to know if the zip file contains shapefiles or other geographic formats.

**Comment by FrankOssie** [comment]
The zip file contains:
- .dbf
- .shp
- .dhx

**Comment by avvertix** [comment]
I executed the test suite on GeoServer 2.17 and our zipped shapefile is working. So to understand a bit better the scenario I need some more information on the file.

Could you please create a GeoFile instance from that file and print the following information

```php
use OneOffTech\GeoServer\GeoFile;

$file = GeoFile::from('/path/to/shapefile.zip');

// print out these attributes
$file->format
$file->type
$file->mimeType
$file->extension
$file->normalizedExtension
$file->normalizedMimeType

// and the return of this method
$file->wasRenamed()
```

In this way we can understand better what the library will send over to GeoServer. 

In addition, if possible, would be nice to have the json response that GeoServer is returning. You could obtain it by dumping it within the [`deserialize` method of the `InteractsWithHttp` trait](https://github.com/OneOffTech/geoserver-client-php/blob/master/src/Http/InteractsWithHttp.php#L84).

**Comment by FrankOssie** [comment]
Ok awesome, and thanks for the fast responses. I'm diving straight into it.

**Comment by FrankOssie** [comment]
object(OneOffTech\GeoServer\GeoFile)#133 (9) {
  ["file":protected]=>
  object(SplFileInfo)#221 (2) {
    ["pathName":"SplFileInfo":private]=>
    string(68) "../files/pimtransfer/1708/templates_bestuurlijkegrenzen_20190204.zip"
    ["fileName":"SplFileInfo":private]=>
    string(42) "templates_bestuurlijkegrenzen_20190204.zip"
  }
  ["name":protected]=>
  string(42) "templates_bestuurlijkegrenzen_20190204.zip"
  ["originalName":protected]=>
  string(42) "templates_bestuurlijkegrenzen_20190204.zip"
  ["mimeType":protected]=>
  string(15) "application/zip"
  ["format":protected]=>
  string(13) "shapefile_zip"
  ["extension":protected]=>
  string(3) "zip"
  ["normalizedExtension":protected]=>
  string(3) "shp"
  ["normalizedMimeType":protected]=>
  string(15) "application/zip"
  ["type":protected]=>
  string(6) "vector"
}

**Comment by avvertix** [comment]
seems that all the data are inline with the GeoServer expectation.

There are two things that might have an impact:

- Reference coordinate system, maybe it happens something inside GeoServer when recognizing the coordinate system of the shapefile
- lack of some files inside the zip, for example the `prj` file

To this aim have you tried to upload the file from the GeoServer administration UI?

In addition the raw json response could give a deeper view of the error. Inside the vendor folder you could edit the [InteractsWithHttp](https://github.com/OneOffTech/geoserver-client-php/blob/master/src/Http/InteractsWithHttp.php#L84) trait to include a dump of the raw within the `deserialize` method.

**Comment by FrankOssie** [comment]
Ok thnx, just keep the issue open i will test a couple of things

**Comment by avvertix** [comment]
Sure, let me know anything you discover

**Comment by FrankOssie** [comment]
Yes i will, and maybe we can even make a video conference to find it out. I attached a screenshot with the error in the geoserver after uploading it. That was straight after the upload, so maybe there is something wrong in the files.

![Screenshot from 2020-06-26 15-08-04](https://user-images.githubusercontent.com/3169986/85862231-c632a380-b7c1-11ea-8dc8-d176e77f4646.png)

**Comment by avvertix** [comment]
Probably there might be something wrong within the file. An option might worth looking into is to try to upload it to an older GeoServer version (2.15 o 2.16) to see if the problem is the same and/or check with `ogrinfo` what kind of information about the file and the spatial dimensions it reports. Maybe the GeoServer logs include also a stacktrace of the exception.

If you have 3D geometries inside the file, maybe, this issue https://osgeo-org.atlassian.net/browse/GEOT-6362 (discovered from https://gis.stackexchange.com/questions/361732/geoserver-upgraded-to-2-17-wfs-extra-dimension-returned-in-linestrings-causing) could be related to it.

**Comment by FrankOssie** [comment]
Can you maybe supply me a correct zip file? So i can see what is missing from our side.

**Comment by avvertix** [comment]
Under tests/fixtures we have a couple of shapefiles that uploads nicely.

- https://github.com/OneOffTech/geoserver-client-php/blob/master/tests/fixtures/buildings.zip
- https://github.com/OneOffTech/geoserver-client-php/blob/master/tests/fixtures/shapefile.zip

According to the [issue related to 3D objects within the shapefile](https://osgeo-org.atlassian.net/browse/GEOT-6599) the file reported there should fail from rendering, but not from uploading, so might worth to give a try.

**Comment by FrankOssie** [comment]
With the example files the same error occurs.

**Comment by FrankOssie** [comment]
Could you test the same file against the 2.17 geoserver?

**Comment by avvertix** [comment]
I've added 2.17 to our automated test suite in #21 for that and everything seems fine. I will double check locally if the WMS returns data. For the sake of checking on the same version I'm doing tests using the kartoza/geoserver docker image for [2.17.0](https://hub.docker.com/r/kartoza/geoserver/tags)

**Comment by avvertix** [comment]
The image below shows the [buildings.zip](https://github.com/OneOffTech/geoserver-client-php/blob/master/tests/fixtures/buildings.zip) file within GeoServer layer preview.

```
GeoServer Version
2.17.0
Git Revision
6c405bdcd889e3c90099f060cadcaafef13ab321
Build Date
19-Apr-2020 11:07
GeoTools Version
23.0 (rev c19e36629fec6970bd3c8495b600f64c1c36a50e)
GeoWebCache Version
1.17.0 (rev 1.17.x/a83e155a473520caa75cfcb301d32c59a2b16ad5)
```

![image](https://user-images.githubusercontent.com/5672748/85866635-fc732180-b7c7-11ea-9344-829bea187a4d.png)

**Comment by FrankOssie** [comment]
Is there another way we can have contact about the issue?

**Comment by avvertix** [comment]
You could send an email to support@oneofftech.xyz with the file (please remove sensible data). Is important that you share here the following information:

- exact version of GeoServer (the information coming from the about page after login into the administration section of GeoServer)
- the active plugins
- the JSON response returned by GeoServer after the upload (asked already in https://github.com/OneOffTech/geoserver-client-php/issues/20#issuecomment-650042310 and https://github.com/OneOffTech/geoserver-client-php/issues/20#issuecomment-650150393)
- The GeoServer logs

I will try then to upload the file on a clean GeoServer installation to see if I can replicate the error, while sharing the issue with our geospatial expert.

Meanwhile I suggest to try out on a clean GeoServer installation with no plugins. If you are using (or can use) Docker there is [kartoza/geoserver](https://hub.docker.com/r/kartoza/geoserver) which offers very good GeoServer images. These are the ones we are using for the [tests](https://github.com/OneOffTech/geoserver-client-php/blob/master/tests/docker-compose.yml). Please also try with versions below 2.17 so is easier to find the environment under which the error can be replicated.

**Comment by shenriod** [comment]
> The zip file contains:
> 
>     * .dbf
> 
>     * .shp
> 
>     * .dhx

Just a wild guess: a shapefile must consist of at least 3 files: *.shp, *.dbf, *.**s**hx

Since you wrote *.**d**hx , this might be the problem (unless it's just a typo).

Do you have access to another GIS application (QGIS or anything else) to see if your shapefile is working there?
Alternatively, rename dhx into shx and see if that helps, in case it is just the file extension that got wrongly  written
