### ISSUE TITLE
Geoserver behind https proxy apache

### ISSUE THREAD

**Issue by FrankOssie** [OneOffTech/geoserver-client-php#22]
Is there an option to follow permanent redirects? So the upload goes to https instead of http?

**Comment by avvertix** [comment]
If I got correctly you are configuring a GeoServer client with http://mygeoserver and want to let the library automatically follow redirects to https. If so I think that the best option would just configure the GeoServer client instance with the https url by default.

```php
$geoserver = GeoServer::build('https://mygeoserver', 'default');
```

**Comment by FrankOssie** [comment]
I get an internal server error Moved pemanently, so the library does not follow redirects

**Comment by FrankOssie** [comment]
Issue is fixed
