### ISSUE TITLE
failed to install the library

### ISSUE THREAD

**Issue by assia-benseddik** [OneOffTech/geoserver-client-php#23]
hello,
when i run the installation cmd " composer require php-http/guzzle6-adapter guzzlehttp/psr7 http-interop/http-factory-guzzle oneofftech/geoserver-client-php " i get the following error  :

Using version ^2.0 for php-http/guzzle6-adapter
Using version ^2.4 for guzzlehttp/psr7
Using version ^1.2 for http-interop/http-factory-guzzle
Using version ^0.3.0 for oneofftech/geoserver-client-php
./composer.json has been created
Running composer update php-http/guzzle6-adapter guzzlehttp/psr7 http-interop/http-factory-guzzle oneofftech/geoserver-client-php
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-http/guzzle6-adapter v2.0.2 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, ..., 6.5.8].
    - php-http/guzzle6-adapter[v2.0.0, ..., v2.0.1] require php ^7.1 -> your php version (8.1.2) does not satisfy that requirement.
    - guzzlehttp/guzzle[6.0.0, ..., 6.0.1] require guzzlehttp/psr7 ^1.0.0 -> found guzzlehttp/psr7[1.0.0, ..., 1.9.0] but it conflicts with your root composer.json require (^2.4).
    - guzzlehttp/guzzle[6.0.2, ..., 6.2.0] require guzzlehttp/psr7 ~1.1 -> found guzzlehttp/psr7[1.1.0, ..., 1.9.0] but it conflicts with your root composer.json require (^2.4).
    - guzzlehttp/guzzle[6.2.1, ..., 6.2.2] require guzzlehttp/psr7 ^1.3.1 -> found guzzlehttp/psr7[1.3.1, ..., 1.9.0] but it conflicts with your root composer.json require (^2.4).
    - guzzlehttp/guzzle[6.2.3, ..., 6.3.3] require guzzlehttp/psr7 ^1.4 -> found guzzlehttp/psr7[1.4.0, ..., 1.9.0] but it conflicts with your root composer.json require (^2.4).
    - guzzlehttp/guzzle[6.4.0, ..., 6.5.7] require guzzlehttp/psr7 ^1.6.1 -> found guzzlehttp/psr7[1.6.1, ..., 1.9.0] but it conflicts with your root composer.json require (^2.4).
    - guzzlehttp/guzzle 6.5.8 requires guzzlehttp/psr7 ^1.9 -> found guzzlehttp/psr7[1.9.0] but it conflicts with your root composer.json require (^2.4).
    - Root composer.json requires php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1, v2.0.2].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require php-http/guzzle6-adapter:*" to figure out if any version is installable, or "composer require php-http/guzzle6-adapter:^2.1" if you know which you need.

Installation failed, deleting ./composer.json.

i am new to composer could someone help me ??

**Comment by avvertix** [comment]
Is true that you have PHP 8.1? If yes you need to use `php-http/guzzle7-adapter` as guzzle 6 is not compatible with PHP 8.1

> - php-http/guzzle6-adapter v2.0.2 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, ..., 6.5.8].
> - php-http/guzzle6-adapter[v2.0.0, ..., v2.0.1] require php ^7.1 -> **your php version (8.1.2) does not satisfy that requirement.**

**Comment by assia-benseddik** [comment]
Thank you so much that solved my problem
