### ISSUE TITLE
problem during installation

### ISSUE THREAD

**Issue by thomas370** [OneOffTech/geoserver-client-php#33]
here is my error
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hwi/oauth-bundle[1.4.0, ..., 1.4.5] require symfony/framework-bundle ^4.4|^5.1 -> found symfony/framework-bundle[v4.4.0, ..., v4.4.45, v5.1.0, ..., v5.4.12] but it conflicts with your root composer.json require (6.1.*).
    - Root composer.json requires hwi/oauth-bundle ^1.4 -> satisfiable by hwi/oauth-bundle[1.4.0, ..., 1.4.5].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require hwi/oauth-bundle:*" to figure out if any version is installable, or "composer require hwi/oauth-bundle:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by avvertix** [comment]
Hi @thomas370 could you list the full error log as `hwi/oauth-bundle` is not a dependency we rely on. From what I see, from the part of the log you shared, seems to be a Symfony bundle.

**Comment by thomas370** [comment]
yes it's a Symfony bundle but I'm having trouble installing it. I don't have anything more than this error if you have anything to help me I'm available via discord if you want to contact me thomas56#0903 @avvertix

**Comment by avvertix** [comment]
To help you I can give a different explanation of the error that you shared

```
- hwi/oauth-bundle[1.4.0, ..., 1.4.5] require symfony/framework-bundle ^4.4|^5.1 -> found symfony/framework-bundle[v4.4.0, ..., v4.4.45, v5.1.0, ..., v5.4.12] but it conflicts with your root composer.json require (6.1.*).
- Root composer.json requires hwi/oauth-bundle ^1.4 -> satisfiable by hwi/oauth-bundle[1.4.0, ..., 1.4.5].
```

`hwi/oauth-bundle` latest stable release is 1.4.x, which requires `symfony/framework-bundle` 4 or 5 and is not compatible with Symfony 6.1, which you require in your composer.json

From what I can see there is a pre-release you can try, refer to the [composer version constraints](https://getcomposer.org/doc/articles/versions.md) check on how to try it
