### ISSUE TITLE
GeoNetwork with PHP

### ISSUE THREAD

**Issue by anikfal** [OneOffTech/geoserver-client-php#35]
Can `geoserver-client-php` also be used for GeoNetwork?
If not, is there any way to run GeoNetwork by PHP?

**Comment by avvertix** [comment]
As far as I know GeoNetwork has a different Api than GeoServer. However GeoServer might be behind GeoNetwork. The GeoServer client only works with GeoServer.

I guess information on how to access GeoNetwork programmatively can be found in [their community](https://www.geonetwork-opensource.org/community.html)
